Repository memristor/mep3, pull requests merged in 2022-04, with the labels that each got.

#141 Scored point tracking and Scoreboard BT action
  docker/config/shortcuts.sh
  mep3_behavior_tree/assets/strategies/first_strategy.xml
  mep3_behavior_tree/include/mep3_behavior_tree/scoreboard_task_action.hpp
  mep3_behavior_tree/src/mep3_behavior_tree.cpp
  mep3_msgs/CMakeLists.txt
  mep3_msgs/action/Scoreboard.msg
  mep3_simulation/mep3_simulation/resistance_meter_driver.py
  mep3_simulation/mep3_simulation/scoreboard_lcd_driver.py
  mep3_simulation/resource/config_big.urdf
Labels: simulation, planning

#146 Increase gripper connector tolerance and disable snapping
  docker/config/shortcuts.sh
  mep3_behavior_tree/assets/strategies/first_strategy.xml
  mep3_simulation/mep3_simulation/webots_vacuum_pump_driver.py
  mep3_simulation/webots_data/protos/RobotArmMemristor2.proto
Labels: simulation

#142 Add team color support
  mep3_behavior_tree/assets/strategies/first_strategy.xml
  mep3_behavior_tree/include/mep3_behavior_tree/bt_action_node.hpp
  mep3_behavior_tree/include/mep3_behavior_tree/dynamixel_command_action.hpp
  mep3_behavior_tree/include/mep3_behavior_tree/motion_command_action.hpp
  mep3_behavior_tree/include/mep3_behavior_tree/navigate_to_action.hpp
  mep3_behavior_tree/include/mep3_behavior_tree/precise_navigate_to_action.hpp
  mep3_behavior_tree/include/mep3_behavior_tree/team_color_strategy_mirror.hpp
  mep3_behavior_tree/src/mep3_behavior_tree.cpp
  mep3_bringup/launch/robot_launch.py
  mep3_bringup/launch/simulation_launch.py
  mep3_simulation/mep3_simulation/__init__.py
  mep3_simulation/mep3_simulation/match_start_driver.py
  mep3_simulation/mep3_simulation/resistance_meter_driver.py
  mep3_simulation/mep3_simulation/scoreboard_lcd_driver.py
  mep3_simulation/mep3_simulation/webots_cinch_driver.py
  mep3_simulation/mep3_simulation/webots_dynamixel_driver.py
  mep3_simulation/mep3_simulation/webots_replica_driver.py
  mep3_simulation/mep3_simulation/webots_statuette_driver.py
  mep3_simulation/mep3_simulation/webots_vacuum_pump_driver.py
  mep3_simulation/resource/config_big.urdf
  mep3_simulation/webots_data/controllers/camera_controller/camera_controller
  mep3_simulation/webots_data/controllers/judge/judge.py
  mep3_simulation/webots_data/controllers/opponent_robot/opponent_robot.py
  mep3_simulation/webots_data/worlds/eurobot_2022.wbt
Labels: enhancement

#147 Add vacuum pump driver
  mep3_driver/CMakeLists.txt
  mep3_driver/launch/driver_launch.py
  mep3_driver/mep3_driver/vacuum_pump_driver.py
Labels: low level control

#158 Sample static obstacles
  mep3_bringup/resource/map.pgm
  mep3_bringup/resource/map.xcf
Labels: navigation

#161 Resistance meter hardware driver
  docker/config/shortcuts.sh
  mep3_driver/launch/driver_launch.py
  mep3_driver/mep3_driver/resistance_meter_driver.py
Labels: low level control

#162 Fix C++ linter errors
  mep3_behavior_tree/include/mep3_behavior_tree/delay_action.hpp
  mep3_behavior_tree/include/mep3_behavior_tree/navigate_to_action.hpp
Labels: bug

#172 Swap expected team resistances when mirroring strategy
  mep3_behavior_tree/include/mep3_behavior_tree/resistance_meter_action.hpp
  mep3_behavior_tree/include/mep3_behavior_tree/team_color_strategy_mirror.hpp
Labels: planning

#170 Lynxmotion servo driver
  mep3_driver/CMakeLists.txt
  mep3_driver/launch/driver_launch.py
  mep3_driver/mep3_driver/lynx_driver.py
Labels: low level control

#160 Big robot strategy
  mep3_behavior_tree/assets/strategies/big_robot_purple.xml
  mep3_behavior_tree/assets/strategies/big_strategy.xml
  mep3_behavior_tree/assets/strategies/small_robot_purple.xml
  mep3_behavior_tree/assets/strategies/small_strategy.xml
  mep3_behavior_tree/include/mep3_behavior_tree/dynamixel_command_action.hpp
  mep3_behavior_tree/include/mep3_behavior_tree/team_color_strategy_mirror.hpp
  mep3_behavior_tree/include/mep3_behavior_tree/vacuum_pump_command_action.hpp
  mep3_bringup/launch/robot_launch.py
  mep3_bringup/launch/simulation_launch.py
  mep3_bringup/resource/ros2_control_small.yaml
  mep3_driver/launch/driver_launch.py
  mep3_driver/mep3_driver/cinch_driver.py
  mep3_driver/mep3_driver/dynamixel_driver.py
  mep3_driver/mep3_driver/resistance_meter_driver.py
  mep3_driver/mep3_driver/vacuum_pump_driver.py
  mep3_driver/resource/config_small.urdf
  mep3_navigation/include/mep3_navigation/.clang-format
  mep3_navigation/src/distance_angle/.clang-format
  mep3_simulation/mep3_simulation/resistance_meter_driver.py
  mep3_simulation/webots_data/protos/Hand.proto
  mep3_simulation/webots_data/worlds/eurobot_2022.wbt
  tools/dynamixel.py
  tools/position_reader.py
Labels: simulation, planning
