Repository memristor/mep3, pull requests merged in 2022-11, with the labels that each got.

#227 Playing area for 2023
  .gitignore
  docker/config/shortcuts.sh
  mep3_behavior_tree/CMakeLists.txt
  mep3_simulation/launch/simulation_launch.py
  mep3_simulation/resource/config_big.urdf
  mep3_simulation/resource/config_small.urdf
  mep3_simulation/webots_data/controllers/judge/judge.py
  mep3_simulation/webots_data/protos/ArucoTag.proto
  mep3_simulation/webots_data/protos/BasketSupport.proto
  mep3_simulation/webots_data/protos/Cake.proto
  mep3_simulation/webots_data/protos/CentralTrackingDevice.proto
  mep3_simulation/webots_data/protos/Cherry.proto
  mep3_simulation/webots_data/protos/CherrySupport.proto
  mep3_simulation/webots_data/protos/CherrySupports.proto
  mep3_simulation/webots_data/protos/DispenserOuter.proto
  mep3_simulation/webots_data/protos/DispenserVertical.proto
  mep3_simulation/webots_data/protos/ExcavationSquare.proto
  mep3_simulation/webots_data/protos/FixedBeaconSupport.proto
  mep3_simulation/webots_data/protos/FixedBeaconSupports.proto
  mep3_simulation/webots_data/protos/GalleryPanel.proto
  mep3_simulation/webots_data/protos/Hand.proto
  mep3_simulation/webots_data/protos/Lift.proto
  mep3_simulation/webots_data/protos/OmniWheel.proto
  mep3_simulation/webots_data/protos/OpponentBox.proto
  mep3_simulation/webots_data/protos/Replica.proto
  mep3_simulation/webots_data/protos/RobotArmMemristor2.proto
  mep3_simulation/webots_data/protos/RobotMemristor2.proto
  mep3_simulation/webots_data/protos/Sample.proto
  mep3_simulation/webots_data/protos/StaticObjects.proto
  mep3_simulation/webots_data/protos/Statuette.proto
  mep3_simulation/webots_data/protos/StatuetteSupport.proto
  mep3_simulation/webots_data/protos/Wall.proto
  mep3_simulation/webots_data/protos/Walls.proto
  mep3_simulation/webots_data/protos/Wheel.proto
  mep3_simulation/webots_data/worlds/.eurobot_2023.jpg
  mep3_simulation/webots_data/worlds/assets/cakes/brown.png
  mep3_simulation/webots_data/worlds/assets/cakes/pink.png
  mep3_simulation/webots_data/worlds/assets/cakes/yellow.png
  mep3_simulation/webots_data/worlds/assets/table.png
  mep3_simulation/webots_data/worlds/eurobot_2022.wbt
  mep3_simulation/webots_data/worlds/eurobot_2023.wbt
  mep3_simulation/webots_data/worlds/test_controller.wbt
  mep3_simulation/webots_data/worlds/test_opponent_robot.wbt
  mep3_simulation/webots_data/worlds/test_robot.wbt
  mep3_simulation/webots_data/worlds/test_robot_arm_memristor.wbt
Labels: simulation

#228 New Docker development environment
  docker/Dockerfile
  docker/Makefile
  docker/README.md
  docker/config/Cyberobotics/Webots-R2022b.conf
  docker/config/ps1.sh
  docker/config/setup.sh
  docker/config/shortcuts.sh
  docker/config/vnc.sh
  docker/config/vscode/c_cpp_properties.json
  docker/entrypoint.sh
  docker/provision/devel.mk
  docker/provision/docker.mk
  docker/provision/mep3.mk
  docker/provision/ros2.mk
  docker/provision/vnc.mk
Labels: enhancement, devops

#232 Docker container flavors
  docker/Makefile
  docker/README.md
  docker/config/bashrc
  docker/config/setup.sh
  docker/config/vnc.sh
Labels: devops
