Repository memristor/mep3, pull requests merged in 2024-03, with the labels that each got.

#290 Disable ROS first time setup by default
  docker/Dockerfile.base
  docker/Makefile
  docker/config/bashrc
  docker/config/setup.sh
Labels: bug, devops

#293 Feature try implement stuck and fix bugs
  mep3_behavior/src/mep3_behavior_tree.cpp
  mep3_behavior/strategies/init.xml
  mep3_behavior/strategies/project.btproj
  mep3_behavior/strategies/try_move_weed.xml
  mep3_behavior/strategies/try_plenter.xml
  mep3_behavior/strategies/try_put_plenter.xml
  mep3_behavior/strategies/try_put_simple.xml
  mep3_behavior/strategies/try_translate.xml
  mep3_bringup/launch/robot_launch.py
  mep3_hardware/launch/hardware_launch.py
  mep3_hardware/resource/big_controllers.yaml
  mep3_hardware/resource/big_description.urdf
  mep3_navigation/launch/navigation_launch.py
  mep3_navigation/src/move/move.cpp
  mep3_navigation/src/move/move.hpp
  mep3_simulation/webots_data/controllers/judge/judge.py
  mep3_simulation/webots_data/worlds/eurobot.wbt
Labels: navigation

#295 Add Groot2 to Docker image
  docker/Dockerfile.base
  docker/Makefile
  docker/README.md
  docker/config/setup.sh
Labels: devops
